# Generated by Django 4.2.13 on 2024-07-03 15:20

import auto_prefetch
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0001_initial"),
        ("ecommerce", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="user",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User Post",
            ),
        ),
        migrations.AddField(
            model_name="blogcategory",
            name="sub_category",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="blog.blogcategory",
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="category",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ecommerce.category",
                verbose_name="Banner category",
            ),
        ),
    ]
