# Generated by Django 4.2.13 on 2024-06-27 18:43

import auto_prefetch
from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ecommerce", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="user",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="productreview",
            name="product",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ecommerce.product",
                verbose_name="Product Review",
            ),
        ),
        migrations.AddField(
            model_name="productreview",
            name="user",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User Review",
            ),
        ),
        migrations.AddField(
            model_name="productimages",
            name="product",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ecommerce.product",
                verbose_name="Product image",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ecommerce.category",
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="user",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="order",
            field=auto_prefetch.OneToOneField(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="ecommerce.cartorder",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="user",
            field=auto_prefetch.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="sub_category",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="ecommerce.category",
            ),
        ),
        migrations.AddField(
            model_name="cartorderitems",
            name="order",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="ecommerce.cartorder",
                verbose_name="Order",
            ),
        ),
        migrations.AddField(
            model_name="cartorderitems",
            name="product",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ecommerce.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="user",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User Order",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="user",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User Address",
            ),
        ),
    ]
