# Generated by Django 4.2.13 on 2024-07-06 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0003_productkey_is_used"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="spacification",
            new_name="specification",
        ),
        migrations.RemoveField(
            model_name="product",
            name="unique_keys",
        ),
    ]
