# Generated by Django 4.2.13 on 2024-07-07 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0004_rename_spacification_product_specification_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartorderitems",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Cart Order Items",
            },
        ),
        migrations.AlterField(
            model_name="cartorderitems",
            name="transaction_id",
            field=models.CharField(
                blank=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
