# Generated by Django 4.2.13 on 2024-07-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0005_alter_cartorderitems_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at", "-updated_at"],
                "permissions": [
                    ("can_crud_product", "Can create, update, and delete product")
                ],
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AddField(
            model_name="cartorder",
            name="payment_method",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
