# Generated by Django 4.2.13 on 2024-07-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0006_alter_product_options_cartorder_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartorderitems",
            name="keys_and_passwords",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
