# Generated by Django 4.2.13 on 2024-07-14 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0007_cartorderitems_keys_and_passwords"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tags",
        ),
    ]
