# Generated by Django 4.2.13 on 2024-08-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0009_payment_payment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
