# Generated by Django 4.2.13 on 2024-08-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0011_alter_payment_payment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
