# Generated by Django 4.2.13 on 2024-06-27 18:43

import auto_prefetch
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="assigned_to",
            field=auto_prefetch.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="users.customersupportrepresentative",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="customer",
            field=auto_prefetch.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="ticket",
            field=auto_prefetch.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responses",
                to="support.ticket",
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="user",
            field=auto_prefetch.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
