# Generated by Django 4.2.13 on 2024-07-14 03:01

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="", max_length=100, null=True)),
                ("email", models.EmailField(default="", max_length=254, null=True)),
                ("subject", models.CharField(default="", max_length=255, null=True)),
                ("message", models.TextField(default="", null=True)),
            ],
            options={
                "verbose_name": "Contact us",
                "verbose_name_plural": "Contact us",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
